wandb_version: 1

logging:
  desc: null
  value:
    project_name: colo_vs_gastro
model:
  desc: null
  value:
    name: resnet18
    pretrained: true
    number_of_classes: 3
    mutually_exclusive: true
data:
  desc: null
  value:
    images_directory: /media/yanny/Extreme SSD/colo_vs_gastro/data
    annotations_path: /media/yanny/Extreme SSD/colo_vs_gastro/CV-Base/data/classification_data.json
    validation_folds:
    - 0
    - 1
    test_folds:
    - 9
transforms:
  desc: null
  value:
    width: 224
    height: 224
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
optimizer:
  desc: null
  value:
    name: AdamW
    learning_rate: 0.001
    weight_decay: 0.0002
    eta_min: 1.0e-06
training:
  desc: null
  value:
    max_epochs: 3
    device: cuda
    checkpoint_directory: ./checkpoints
    save_top_k: 1
    precision: 16
dataloading:
  desc: null
  value:
    train_batch_size: 256
    valid_batch_size: 256
    test_batch_size: 256
    train_workers: 4
    valid_workers: 4
    test_workers: 4
    pin_memory: true
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686125023.088759
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.15.3
      6: 4.24.0
      8:
      - 5
