[logging]
project_name = "num_cuts_verified_data"

[model]
name = "vit_tiny_patch16_384"
pretrained = true
number_of_classes = 2
mutually_exclusive = true

[data]
images_directory = "/media/yanny/BackUp3/Polypectomy Quality Predictor/Snare_Resections_Data/snare_resections"
annotations_path = "/media/yanny/BackUp3/Polypectomy Quality Predictor/Predictor_Number_of_Cuts/data/train_data.json"
validation_folds = [1, 4]
test_folds = []
label_names = ["negative", "positive"]

[transforms]
width = 384
height = 384
mean = [0.45211223, 0.27139644, 0.19264949]
std = [0.31418097, 0.21088019, 0.16059452]

[optimizer]
name = "AdamW"
learning_rate = 0.0004
weight_decay = 0.0002
eta_min = 0.000001
use_scheduler = true


[training]
max_epochs = 100
device = "cuda"
checkpoint_directory = "./checkpoints"
save_top_k = 1
precision = "16-mixed"
stopping_patience = 0


[dataloading]
train_batch_size = 25
valid_batch_size = 25
test_batch_size = 25

train_workers = 4
valid_workers = 4
test_workers = 4

pin_memory = true



