[logging]
project_name = "colo_vs_gastro"

[model]
name = "resnet18"
pretrained = true
number_of_classes = 3
mutually_exclusive = true

[data]
images_directory = "/media/yanny/Extreme SSD/colo_vs_gastro/data"
annotations_path = "/media/yanny/Extreme SSD/colo_vs_gastro/CV-Base/data/classification_data.json"
validation_folds = [0, 1]
test_folds = [9]

[transforms]
width = 416
height = 320
mean = [0.45211223, 0.27139644, 0.19264949]
std = [0.31418097, 0.21088019, 0.16059452]

[optimizer]
name = "AdamW"
learning_rate = 0.001
weight_decay = 0.0002
eta_min = 0.000001

[training]
max_epochs = 3
device = "cuda"
checkpoint_directory = "./checkpoints"
save_top_k = 1
precision = 16


[dataloading]
train_batch_size = 256
valid_batch_size = 256
test_batch_size = 256

train_workers = 4
valid_workers = 4
test_workers = 4

pin_memory = true



